linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - goimports
    - misspell
    - prealloc
    - exportloopref
    - revive

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - testdata/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
  gosec:
    excludes:
      - G404  # Use of weak random number generator
