linters:
  enable:
    - gofmt
    - govet
    - golint
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - unconvert
    - misspell
    - gosec

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - test/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
