apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: rdap
spec:
  ports:
  - port: 9092
    name: kafka
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: rdap
spec:
  ports:
  - port: 9092
    name: kafka
  selector:
    app: kafka
