apiVersion: v1
kind: ConfigMap
metadata:
  name: rdap-config
  namespace: rdap
data:
  CACHE_TTL: "3600"
  MAX_CONCURRENT_REQUESTS: "5000"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  REDIS_URL: "redis.rdap.svc.cluster.local:6379"
  KAFKA_BROKERS: "kafka-0.kafka.rdap.svc.cluster.local:9092,kafka-1.kafka.rdap.svc.cluster.local:9092,kafka-2.kafka.rdap.svc.cluster.local:9092"
  KAFKA_ENABLED: "true"
  KAFKA_TOPIC: "rdap-events"
  KAFKA_GROUP_ID: "rdap-consumer"
