apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdap-server
  namespace: rdap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rdap-server
  template:
    metadata:
      labels:
        app: rdap-server
    spec:
      containers:
      - name: rdap-server
        image: rdap:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        envFrom:
        - configMapRef:
            name: rdap-config
        volumeMounts:
        - name: bootstrap-config
          mountPath: /app/config
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: bootstrap-config
        configMap:
          name: rdap-bootstrap-config
---
apiVersion: v1
kind: Service
metadata:
  name: rdap-service
  namespace: rdap
  labels:
    app: rdap-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 31080
    - name: metrics
      port: 9090
      targetPort: metrics
      nodePort: 31090
  selector:
    app: rdap-server
