apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: rdap
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  selector:
    app: zookeeper
  clusterIP: None
